good = """Air quality is considered satisfactory, and air pollution poses little or no risk"""
moderate = """Air quality is acceptable; however, for some pollutants there may be a moderate health concern for a very small number of people who are unusually sensitive to air pollution."""
unhealthy_sensitive = """Members of sensitive groups may experience health effects. The general public is not likely to be affected."""
unhealthy = """	Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects"""
very_unhealthy = """Health warnings of emergency conditions. The entire population is more likely to be affected."""
hazardous = """	Health alert: everyone may experience more serious health effects"""
